"use client";
import "./globals.css";
import { Schibsted_Grotesk } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useEffect, useRef, useState } from "react";
import { MyContext } from "./context";

const inter = Schibsted_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  const headerRef = useRef(null);
  const footerRef = useRef(null);
  const videoRef = useRef(null);
  const docRef = useRef(null);
  const [offset, setOffset] = useState(0);
  const [observer, setObserver] = useState(null);

  const onScroll = () => {
    const st = window.pageYOffset || document.documentElement.scrollTop;
    if (st > offset) {
      // downscroll code
      headerRef.current.style.transform = "translateY(-100%)";
    } else if (st < offset) {
      headerRef.current.style.transform = "translateY(0)";
    }

    setOffset(st <= 0 ? 0 : st);
  };

  useEffect(() => {
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, [offset]);

  useEffect(() => {
    const options = {
      root: null,
      rootMargin: "0px",
      threshold: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
    };

    setObserver(
      new IntersectionObserver((entries, observer) => {
        entries.forEach((item) => {
          if (
            item.isIntersecting &&
            item.target === footerRef.current &&
            item.intersectionRatio >= 0.85
          ) {
            headerRef.current.style.background = "white";
            headerRef.current.style.color = "black";
          } else if (
            item.target === videoRef.current &&
            item.isIntersecting &&
            item.intersectionRatio >= 0.3
          ) {
            headerRef.current.style.background = "transparent";
            headerRef.current.style.color = "white";
          }
          console.log(entries);
        });
      }, options)
    );
  }, []);

  return (
    <html lang="en">
      <body className={inter.className} ref={docRef}>
        <MyContext.Provider
          value={{
            headerRef: headerRef,
            footerRef: footerRef,
            videoRef: videoRef,
            observer: observer,
          }}
        >
          <div className="w-[100%] flex flex-col">
            <Header />
            {children}
            <Footer />
          </div>
        </MyContext.Provider>
      </body>
    </html>
  );
};
export default RootLayout;
